plugins:
  - rubocop-minitest
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "lib/generators/**/templates/**"
    - "demo/**/*"
    - "vendor/**/*"
    - "docs/node_modules/**/*"

Style/Documentation:
  Enabled: false

Style/OneClassPerFile:
  Exclude:
    - "test/**/*"

Lint/EmptyClass:
  Exclude:
    - "test/**/*"

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "*.gemspec"

Metrics/AbcSize:
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Exclude:
    - "test/**/*"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"

Metrics/ParameterLists:
  CountKeywordArgs: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
